name: PyPI Publication

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on version tags like v1.0.0

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Needed to access repository content

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools twine

      # Step 4: Build the package
      - name: Build the package
        run: |
          python -m build

      # Step 5: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
        run: |
          twine upload --non-interactive dist/*
